### ISSUE TITLE
Can you share ground truth in SOD dataset?

### ISSUE THREAD

**Issue by YoucanBaby** [OliverRensu/GLSTR#2]
Hello!
Can you share ground truth in SOD dataset?
It's too hard to me to process SOD dataset.
Can you help me?
Thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!🙇‍

**Comment by OliverRensu** [comment]
You can download from  https://drive.google.com/file/d/18YwMduF2knjTei0AdC_7ZeoyACq9py0O/view?usp=sharing
